image: docker:stable

stages:
  - build
  - push

# master-info
build_image_master-info:
  stage: build
  script:
    - echo "Building image - $CI_REGISTRY_IMAGE:master-info"
    - docker image build -f Dockerfile -t "$CI_REGISTRY_IMAGE:master-info" .
  only:
    - master-info

push_image_master-info:
  stage: push
  script:
    - echo "Pushing image"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY_URL"
    - docker image push "$CI_REGISTRY_IMAGE:master-info"
  only:
    - master-info



